version: "2"
services: 
  web:
    build: .
    depends_on: 
      - mongo
    ports: 
      - "3000:3000"
    volumes: 
      - .:/opt/app
      - /opt/app/node_modules
  mongo:
    image: mongo
    expose: 
      - "27017"
    ports: 
      - "27018:27017"
    volumes: 
      - mongodata:/data/db
volumes: 
  mongodata:
